version: '3'
services:
  web:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/web
    container_name: web
  client:
    build: ./client
    ports:
      - "3001:3001"
    volumes:
      - ./client:/client
    container_name: client
